### ISSUE TITLE
experimental code

### ISSUE THREAD

**Issue by T1ROSE** [Chenyang4/ReSmooth#1]
Hello,

Thanks for sharing the code. Can you share the experimental code of the augmentation strategy based on TeachAugment?

I am truely thankful.

Thanks.

**Comment by Chenyang4** [comment]
Hello, 

Please see [here](https://github.com/Chenyang4/RSTA) for the experimental code. Due to the complexity of TeachAugment, we perform experiments on its code base.

Hope it will help you.
